name: inter_war
description: Uma aplicação para iano se divertir.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  json_annotation: 4.1.0
  uuid: ^3.0.6

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: 2.1.5
  json_serializable: 4.1.4

flutter:
  uses-material-design: true
